dicionario_de_erros = {
    2:"API Key nao informada - Parâmetro api key não foi encontrado",
    3:"API Key invalida",
    4:"Método não disponível em HTTP, utilize HTTPS - Somente chamadas para HTTPS sao aceitas",
    5:"Tipo de request (POST, GET, PUT, DELETE) esta incorreto",
    6:"MethodNotFound - Método nao encontrado - O método da chamada não existe",
    7:"Método POST não disponível para esta API",
    8:"Método GET não disponível para esta API",
    9:"Método PUT não disponível para esta API",
    10:"Método DELETE não disponível para esta API",
    11:"Para a execução desta função e necessário a passagem de mais parâmetros. Consulte a documentação",
    12:"Parâmetro(s) e(são) invalido(s)",
    13:"Formato de retorno incorreto. O retorno pode ser em XML ou JSON",
    14:"A informação desejada não foi encontrada",
    15:"Recurso não disponível para esta API",
    16:"Você não tem permissão para acessar a API",
    17:"Os filtros inseridos sao invalidos. Consulte a documentacao",
    18:"O limite de requisicoes foi atingido",
    19:"Usuário não possui permissão para acessar o método informado",
    20:"Método http não suportado para esta API",
    21:"Este endereço IP não possui permissão para acessar a API"}
