# Generated by Django 4.0 on 2022-02-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0002_alter_contato_id_bling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='ie_rg',
            field=models.CharField(blank=True, default='', max_length=18, null=True),
        ),
    ]
