# Generated by Django 4.0 on 2022-02-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0002_alter_produto_codigo_fabricante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id_fabricante',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='produtokit',
            name='id_fabricante',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
