# Generated by Django 4.0 on 2022-02-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0003_alter_contato_ie_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='cpf_cnpj',
            field=models.CharField(blank=True, default='', max_length=18, null=True),
        ),
    ]
