# Generated by Django 4.0 on 2022-02-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0003_alter_produto_id_fabricante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_pedido_loja',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='situacao',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_integracao',
            field=models.CharField(default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_produtos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_venda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.CharField(default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_saida',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
