# Generated by Django 4.0 on 2022-02-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0004_pedido_numero_pedido_loja_pedido_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=11, null=True),
        ),
    ]
