# Generated by Django 4.0 on 2022-02-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0005_alter_pedido_data_alter_pedido_data_saida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='numero_loja',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='loja',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
