# Generated by Django 4.0 on 2022-02-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0006_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
