# Generated by Django 4.0 on 2022-02-17 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0006_remove_pedido_numero_loja_alter_pedido_loja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bling.pedido'),
        ),
    ]
