# Generated by Django 4.0 on 2022-02-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0007_alter_item_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='vlr_desconto',
            field=models.CharField(default='0%', max_length=20, null=True),
        ),
    ]
