# Generated by Django 4.0 on 2022-02-17 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0009_alter_pedido_numero_pedido_loja'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bling', models.IntegerField(null=True)),
                ('situacao', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('vencimento', models.DateTimeField(blank=True, null=True)),
                ('competencia', models.DateTimeField(blank=True, null=True)),
                ('nro_documento', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('historico', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('categoria', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('portador', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ocorrencia', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dia_vencimento', models.DateTimeField(blank=True, null=True)),
                ('nro_parcelas', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bling', models.IntegerField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('codigo_fiscal', models.IntegerField(blank=True, null=True)),
                ('padrao', models.IntegerField(blank=True, null=True)),
                ('situacao', models.IntegerField(blank=True, null=True)),
                ('fixa', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('total_juro', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('total_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('total_acrescimo', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('total_tarifa', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('conta_pagar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bling.contapagar')),
            ],
        ),
        migrations.AddField(
            model_name='contapagar',
            name='forma_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bling.formapagamento'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bling.contato'),
        ),
        migrations.CreateModel(
            name='Bordero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bling.pagamento')),
            ],
        ),
    ]
