# Generated by Django 4.0 on 2022-02-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0010_contapagar_formapagamento_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contapagar',
            name='dia_vencimento',
        ),
    ]
