# Generated by Django 4.0 on 2022-02-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bling', '0011_remove_contapagar_dia_vencimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bling', models.IntegerField(null=True)),
                ('situacao', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('vencimento', models.DateTimeField(blank=True, null=True)),
                ('competencia', models.DateTimeField(blank=True, null=True)),
                ('nro_documento', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('historico', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('categoria', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('portador', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('nro_banco', models.IntegerField(null=True)),
                ('ocorrencia', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('nro_parcelas', models.IntegerField(blank=True, null=True)),
                ('link_boleto', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('vendedor', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bling.contato')),
                ('forma_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bling.formapagamento')),
            ],
        ),
    ]
